"""add profile to usermodel

Revision ID: 2f7bb2f65fc3
Revises: 1f850eeb0f5b
Create Date: 2025-06-08 10:46:55.971461

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f7bb2f65fc3'
down_revision: Union[str, None] = '1f850eeb0f5b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
