"""add default value for uuid field for moviemodel

Revision ID: 532f138e013a
Revises: 24a4a04f69c6
Create Date: 2025-06-09 11:36:08.405065

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '532f138e013a'
down_revision: Union[str, None] = '24a4a04f69c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
