"""add user to ordermodel

Revision ID: 64baa7a72a31
Revises: aaaf8d27dad7
Create Date: 2025-06-08 11:32:38.095020

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '64baa7a72a31'
down_revision: Union[str, None] = 'aaaf8d27dad7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
