"""fix comments back relations name

Revision ID: 7cb3a91946e7
Revises: 5dbdf67bf82b
Create Date: 2025-06-09 21:51:33.540702

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7cb3a91946e7'
down_revision: Union[str, None] = '5dbdf67bf82b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
