"""add cartitem to cartmodel

Revision ID: 9b7db1b664b2
Revises: 2f7bb2f65fc3
Create Date: 2025-06-08 10:50:30.404093

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b7db1b664b2'
down_revision: Union[str, None] = '2f7bb2f65fc3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
