"""add order to paymentmodel

Revision ID: aaaf8d27dad7
Revises: 9b7db1b664b2
Create Date: 2025-06-08 10:55:48.410248

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aaaf8d27dad7'
down_revision: Union[str, None] = '9b7db1b664b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
