"""add passwordresettoken to usermodel

Revision ID: bd212e644b8f
Revises: 4def95e1a59d
Create Date: 2025-06-08 10:38:42.981616

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd212e644b8f'
down_revision: Union[str, None] = '4def95e1a59d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
