"""add movie to orderitemmodel

Revision ID: f0d1f93d7bc4
Revises: f7dccadb966b
Create Date: 2025-06-08 10:14:38.444764

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f0d1f93d7bc4'
down_revision: Union[str, None] = 'f7dccadb966b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
