"""add orderitems to ordermodel

Revision ID: fb77e59cf8eb
Revises: 3b039e27c153
Create Date: 2025-06-08 11:42:17.168634

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb77e59cf8eb'
down_revision: Union[str, None] = '3b039e27c153'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
